import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { supabase } from "@/lib/supabase/client";
import { avecTimeout } from "@/lib/timeout";
import { enregistrerActivite } from "@/lib/audit/journal";

export type InfosBoutique = {
  nom: string;
  telephone: string | null;
  email: string | null;
  secteur: string | null;
  logo: string | null; // data URI (base64)
};

// Récupère les infos de l'entreprise : nom, contact, secteur et logo.
// Le logo est stocké localement (AsyncStorage) ; s'il manque, on affiche
// simplement le nom de la boutique en en-tête.
const CLE_INFOS = "boutika_infos";

async function infosDepuisSupabase(): Promise<InfosBoutique> {
  let nom = "Ma boutique";
  let telephone: string | null = null;
  let email: string | null = null;
  let secteur: string | null = null;

  try {
    // Timeout : hors ligne, getUser peut rester pendu et bloquer l'export.
    const {
      data: { user },
    } = await avecTimeout(supabase.auth.getUser(), 5000);
    if (user) {
      const { data } = await avecTimeout(supabase.from("profiles").select("*").eq("id", user.id).single(), 5000);
      if (data) {
        nom = data.nom_boutique || nom;
        telephone = data.telephone;
        email = data.email ?? user.email;
        secteur = data.secteur;
      }
    }
  } catch {
    // Hors ligne : on garde les valeurs par défaut.
  }

  // Le base64 local prime (le PDF fonctionne hors ligne) ; sinon l'URL distante.
  const logo =
    (await AsyncStorage.getItem("boutika_logo_base64")) ??
    (await AsyncStorage.getItem("boutika_logo"));
  return { nom, telephone, email, secteur, logo };
}

export async function obtenirInfosBoutique(): Promise<InfosBoutique> {
  // 1. Cache local : retour immédiat — imprimer ne doit jamais attendre le réseau.
  const cache = await AsyncStorage.getItem(CLE_INFOS);
  if (cache) {
    // Rafraîchit en arrière-plan pour la prochaine fois (non bloquant).
    infosDepuisSupabase()
      .then((infos) => AsyncStorage.setItem(CLE_INFOS, JSON.stringify(infos)))
      .catch(() => {});
    return JSON.parse(cache) as InfosBoutique;
  }

  // 2. Premier appel (pas encore de cache) : on va chercher puis on met en cache.
  const infos = await infosDepuisSupabase();
  AsyncStorage.setItem(CLE_INFOS, JSON.stringify(infos)).catch(() => {});
  return infos;
}

function enteteHtml(infos: InfosBoutique, titre: string, sousTitre?: string): string {
  const logoHtml = infos.logo
    ? `<img src="${infos.logo}" style="width:64px;height:64px;object-fit:cover;border-radius:8px;" />`
    : `<div style="width:64px;height:64px;border-radius:8px;background:#25af93;color:#fff;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:bold;">${(infos.nom || "M").charAt(0).toUpperCase()}</div>`;

  return `
    <div style="display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #25af93;padding-bottom:12px;margin-bottom:8px;">
      <div style="display:flex;align-items:center;gap:12px;">
        ${logoHtml}
        <div>
          <div style="font-size:20px;font-weight:bold;color:#1A1A18;">${infos.nom}</div>
          ${infos.secteur ? `<div style="font-size:12px;color:#6B6A64;">${infos.secteur}</div>` : ""}
        </div>
      </div>
      <div style="text-align:right;font-size:11px;color:#6B6A64;">
        ${infos.telephone ? `<div>${infos.telephone}</div>` : ""}
        ${infos.email ? `<div>${infos.email}</div>` : ""}
      </div>
    </div>
    <div style="margin-bottom:20px;">
      <div style="font-size:16px;font-weight:bold;color:#1A1A18;">${titre}</div>
      ${sousTitre ? `<div style="font-size:12px;color:#6B6A64;">${sousTitre}</div>` : ""}
    </div>`;
}

// Libellés bilingues du PDF (contexte document, indépendant de l'UI).
const L = {
  fr: {
    facture: "FACTURE", produit: "Produit", qte: "Qté", prixUnitaire: "Prix unitaire", montant: "Montant",
    sousTotal: "Sous-total", remise: "Remise", total: "Total", client: "Client", telephone: "Téléphone",
    localite: "Localité", entreprise: "Entreprise",
    mentions: "Mentions légales — vos données sont traitées conformément à notre politique de confidentialité. Document généré par CIKAP.",
  },
  en: {
    facture: "INVOICE", produit: "Product", qte: "Qty", prixUnitaire: "Unit price", montant: "Amount",
    sousTotal: "Subtotal", remise: "Discount", total: "Total", client: "Client", telephone: "Phone",
    localite: "Locality", entreprise: "Company",
    mentions: "Legal notice — your data is processed in accordance with our privacy policy. Document generated by CIKAP.",
  },
};

function piedHtml(langue: "fr" | "en" = "fr"): string {
  return `<div style="margin-top:30px;padding-top:12px;border-top:1px solid #E5E3DC;font-size:9px;color:#9B9A93;text-align:center;line-height:1.5;">${L[langue].mentions}</div>`;
}

// Bloc client : nom, téléphone, localité (deux colonnes entreprise | client).
function blocClientHtml(facture: any, langue: "fr" | "en"): string {
  const l = L[langue];
  const lignes = [
    facture.clientNom ?? "",
    facture.clientTelephone ? `${l.telephone} : ${facture.clientTelephone}` : "",
    facture.clientLocalite ? `${l.localite} : ${facture.clientLocalite}` : "",
  ].filter(Boolean);
  if (lignes.length === 0) return "";
  return `
    <div style="margin:16px 0;padding:12px;border:1px solid #E5E3DC;border-radius:8px;background:#FAFAF8;">
      <div style="font-size:11px;font-weight:bold;color:#6B6A64;margin-bottom:4px;">${l.client}</div>
      ${lignes.map((x) => `<div style="font-size:12px;color:#1A1A18;">${x}</div>`).join("")}
    </div>`;
}

const STYLE = `<style>
  * { font-family: Arial, sans-serif; }
  body { padding: 24px; color: #1A1A18; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { text-align: left; font-size: 11px; color: #6B6A64; padding: 8px 6px; border-bottom: 1px solid #E5E3DC; }
  td { font-size: 12px; padding: 8px 6px; border-bottom: 1px solid #F0EFEA; }
  .droite { text-align: right; }
  .total { font-size: 14px; font-weight: bold; }
</style>`;

async function partager(html: string, nomFichier: string, ticket = false) {
  const options = ticket
    ? { html, width: LARGEUR_TICKET_PT, height: HAUTEUR_TICKET_PT }
    : { html };
  const { uri } = await Print.printToFileAsync(options);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: nomFichier });
  }
}

// Envoie directement vers l'écran d'impression du téléphone (sans partage).
async function imprimerDirectement(html: string, ticket = false) {
  await Print.printAsync(ticket ? { html, width: LARGEUR_TICKET_PT, height: HAUTEUR_TICKET_PT } : { html });
}

// Format « ticket de caisse » thermique : largeur standard 80 mm (≈ 227 pt),
// PAS du A4. expo-print prend les dimensions de page en points.
const LARGEUR_TICKET_PT = 227; // 80 mm
const HAUTEUR_TICKET_PT = 842; // hauteur de page (pagination automatique)

// Style « ticket de caisse » (modèle : assets/facture.jpg) — bande étroite
// type reçu thermique : police monospace, en-tête centré, séparateurs en
// pointillés, TOTAL en gros, mode de paiement, date centrée en bas.
const STYLE_TICKET = `<style>
  @page { size: 80mm auto; margin: 0; }
  * { font-family: "Courier New", Courier, monospace; color: #1a1a1a; }
  body { width: 80mm; margin: 0; padding: 10px 8px; }
  .centre { text-align: center; }
  .boutique { font-size: 17px; font-weight: bold; text-transform: uppercase; }
  .contact { font-size: 11px; }
  .separateur { border-top: 1px dashed #1a1a1a; margin: 10px 0; }
  .ligne { display: flex; justify-content: space-between; font-size: 12px; padding: 2px 0; }
  .ligne .detail { color: #444; font-size: 10px; }
  .total { font-size: 20px; font-weight: bold; padding: 6px 0; }
  .paiement { font-size: 12px; text-transform: uppercase; }
  .date { text-align: center; font-size: 12px; margin-top: 12px; }
  .merci { text-align: center; font-size: 9px; color: #555; margin-top: 14px; line-height: 1.5; }
</style>`;

// Génère une facture PDF au format ticket de caisse. Par défaut, ouvre
// directement l'écran d'impression ; `exporter = true` génère un fichier à
// partager/télécharger.
export async function genererFacturePdf(facture: any, lignes: any[], langue: "fr" | "en" = "fr", exporter = false) {
  const infos = await obtenirInfosBoutique();
  const l = L[langue];

  const date = facture.creeLe ? new Date(facture.creeLe) : new Date();
  const dateFormatee = `${String(date.getDate()).padStart(2, "0")}/${String(date.getMonth() + 1).padStart(2, "0")}/${date.getFullYear()}`;

  // Chaque article : nom (+ détail « qté × prix unitaire ») et montant à droite.
  const lignesHtml = lignes
    .map(
      (x) => `<div class="ligne">
        <div>
          <div>${x.produitNom}</div>
          <div class="detail">${x.quantite} × ${(x.prixUnitaire || 0).toLocaleString()} F</div>
        </div>
        <div>${((x.quantite || 0) * (x.prixUnitaire || 0)).toLocaleString()} F</div>
      </div>`
    )
    .join("");

  const clientHtml = facture.clientNom
    ? `<div class="ligne"><div>${l.client}</div><div>${facture.clientNom}</div></div>
       ${facture.clientTelephone ? `<div class="ligne"><div>${l.telephone}</div><div>${facture.clientTelephone}</div></div>` : ""}`
    : "";

  const html = `<html><head>${STYLE_TICKET}</head><body>
    <div class="centre">
      <div class="boutique">${infos.nom}</div>
      ${infos.telephone ? `<div class="contact">${infos.telephone}</div>` : ""}
      ${infos.email ? `<div class="contact">${infos.email}</div>` : ""}
    </div>
    <div class="separateur"></div>
    <div class="ligne"><div>${l.facture}</div><div>${facture.numero}</div></div>
    ${clientHtml}
    <div class="separateur"></div>
    ${lignesHtml}
    <div class="separateur"></div>
    ${facture.remise ? `<div class="ligne"><div>${l.remise}</div><div>- ${facture.remise.toLocaleString()} F</div></div>` : ""}
    <div class="ligne total"><div>${l.total}</div><div>${(facture.total || 0).toLocaleString()} F</div></div>
    <div class="ligne paiement"><div>${facture.statut === "payee" ? l.total : l.sousTotal}</div><div>${(facture.montantPaye || 0).toLocaleString()} F</div></div>
    <div class="date">${dateFormatee}</div>
    <div class="merci">${l.mentions}</div>
  </body></html>`;

  if (exporter) {
    await partager(html, `Facture-${facture.numero}.pdf`, true);
  } else {
    await imprimerDirectement(html, true);
  }
  await enregistrerActivite("impression", "ajout", `Facture ${facture.numero} imprimée`);
}

// Génère et partage un export comptable PDF (document complet).
export async function genererExportPdf(
  stats: {
    ca: number; benefice: number; ventes: number; parPaiement: Record<string, number>;
    produitsEnStock?: number; ruptures?: number;
    topProduits?: { nom: string; ventes: number; montant: number }[];
    topClients?: { nom: string; montant: number }[];
  },
  periodeLabel: string
) {
  const infos = await obtenirInfosBoutique();
  const paiementHtml = Object.entries(stats.parPaiement)
    .map(([mode, montant]) => `<tr><td>${mode}</td><td class="droite">${montant.toLocaleString()} F</td></tr>`)
    .join("");

  const topProduitsHtml = (stats.topProduits ?? [])
    .map((p) => `<tr><td>${p.nom}</td><td class="droite">${p.ventes}</td><td class="droite">${p.montant.toLocaleString()} F</td></tr>`)
    .join("");
  const topClientsHtml = (stats.topClients ?? [])
    .map((c) => `<tr><td>${c.nom}</td><td class="droite">${c.montant.toLocaleString()} F</td></tr>`)
    .join("");

  const html = `<html><head>${STYLE}</head><body>
    ${enteteHtml(infos, "EXPORT COMPTABLE", periodeLabel)}
    <table>
      <tr><th>Indicateur</th><th class="droite">Valeur</th></tr>
      <tr><td>Chiffre d'affaires</td><td class="droite">${stats.ca.toLocaleString()} F</td></tr>
      <tr><td>Bénéfice estimé</td><td class="droite">${stats.benefice.toLocaleString()} F</td></tr>
      <tr><td>Nombre de ventes</td><td class="droite">${stats.ventes}</td></tr>
      ${stats.produitsEnStock != null ? `<tr><td>Produits en stock</td><td class="droite">${stats.produitsEnStock}</td></tr>` : ""}
      ${stats.ruptures != null ? `<tr><td>Produits en rupture</td><td class="droite">${stats.ruptures}</td></tr>` : ""}
    </table>
    ${paiementHtml ? `<div style="font-size:13px;font-weight:bold;margin-top:16px;">Par mode de paiement</div><table><tr><th>Mode</th><th class="droite">Montant</th></tr>${paiementHtml}</table>` : ""}
    ${topProduitsHtml ? `<div style="font-size:13px;font-weight:bold;margin-top:16px;">Produits les plus vendus</div><table><tr><th>Produit</th><th class="droite">Ventes</th><th class="droite">Montant</th></tr>${topProduitsHtml}</table>` : ""}
    ${topClientsHtml ? `<div style="font-size:13px;font-weight:bold;margin-top:16px;">Meilleurs clients</div><table><tr><th>Client</th><th class="droite">Montant</th></tr>${topClientsHtml}</table>` : ""}
    ${piedHtml()}
  </body></html>`;

  await partager(html, `Export-comptable.pdf`);
  await enregistrerActivite("impression", "ajout", "Export comptable généré");
}

// Génère et partage un reçu de vente (ticket) PDF.
export async function genererRecuPdf(
  client: string | null,
  telephone: string | null,
  lignes: { nom: string; quantite: number; prixUnitaire: number }[],
  total: number
) {
  const infos = await obtenirInfosBoutique();
  const lignesHtml = lignes
    .map(
      (l) => `<tr>
        <td>${l.nom}</td>
        <td class="droite">${l.quantite}</td>
        <td class="droite">${(l.quantite * l.prixUnitaire).toLocaleString()} F</td>
      </tr>`
    )
    .join("");

  const html = `<html><head>${STYLE}</head><body>
    ${enteteHtml(infos, "REÇU DE VENTE", new Date().toLocaleString())}
    ${client ? `<div style="font-size:12px;margin-bottom:8px;"><b>Client :</b> ${client}${telephone ? ` — ${telephone}` : ""}</div>` : ""}
    <table>
      <tr><th>Produit</th><th class="droite">Qté</th><th class="droite">Montant</th></tr>
      ${lignesHtml}
    </table>
    <table style="width:auto;margin-left:auto;min-width:180px;">
      <tr><td class="total">Total</td><td class="droite total">${total.toLocaleString()} F</td></tr>
    </table>
    ${piedHtml()}
  </body></html>`;

  await partager(html, `Recu-vente.pdf`);
  await enregistrerActivite("impression", "ajout", "Reçu de vente imprimé");
}