import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { supabase } from "@/lib/supabase/client";
import { avecTimeout } from "@/lib/timeout";
import { Platform } from "react-native";
import { enregistrerActivite } from "@/lib/audit/journal";
import { t } from "@/lib/i18n";

export type InfosBoutique = {
  nom: string;
  telephone: string | null;
  email: string | null;
  secteur: string | null;
  logo: string | null; // data URI (base64)
};

// Récupère les infos de l'entreprise : nom, contact, secteur et logo.
// Le logo est stocké localement (AsyncStorage) ; s'il manque, on affiche
// simplement le nom de la boutique en en-tête.
const CLE_INFOS = "boutika_infos";

async function infosDepuisSupabase(): Promise<InfosBoutique> {
  let nom = "Ma boutique";
  let telephone: string | null = null;
  let email: string | null = null;
  let secteur: string | null = null;

  try {
    // Timeout : hors ligne, getUser peut rester pendu et bloquer l'export.
    const {
      data: { user },
    } = await avecTimeout(supabase.auth.getUser(), 5000);
    if (user) {
      const { data } = await avecTimeout(supabase.from("profiles").select("*").eq("id", user.id).single(), 5000);
      if (data) {
        nom = data.nom_boutique || nom;
        telephone = data.telephone;
        email = data.email ?? user.email;
        secteur = data.secteur;
      }
    }
  } catch {
    // Hors ligne : on garde les valeurs par défaut.
  }

  // Le base64 local prime (le PDF fonctionne hors ligne) ; sinon l'URL distante.
  const logo =
    (await AsyncStorage.getItem("boutika_logo_base64")) ??
    (await AsyncStorage.getItem("boutika_logo"));
  return { nom, telephone, email, secteur, logo };
}

export async function obtenirInfosBoutique(): Promise<InfosBoutique> {
  // 1. Cache local : retour immédiat — imprimer ne doit jamais attendre le réseau.
  const cache = await AsyncStorage.getItem(CLE_INFOS);
  if (cache) {
    // Rafraîchit en arrière-plan pour la prochaine fois (non bloquant).
    infosDepuisSupabase()
      .then((infos) => AsyncStorage.setItem(CLE_INFOS, JSON.stringify(infos)))
      .catch(() => {});
    return JSON.parse(cache) as InfosBoutique;
  }

  // 2. Premier appel (pas encore de cache) : on va chercher puis on met en cache.
  const infos = await infosDepuisSupabase();
  AsyncStorage.setItem(CLE_INFOS, JSON.stringify(infos)).catch(() => {});
  return infos;
}

function enteteHtml(infos: InfosBoutique, titre: string, sousTitre?: string): string {
  const logoHtml = infos.logo
    ? `<img src="${infos.logo}" style="width:64px;height:64px;object-fit:cover;border-radius:8px;" />`
    : `<div style="width:64px;height:64px;border-radius:8px;background:#25af93;color:#fff;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:bold;">${(infos.nom || "M").charAt(0).toUpperCase()}</div>`;

  return `
    <div style="display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #25af93;padding-bottom:12px;margin-bottom:8px;">
      <div style="display:flex;align-items:center;gap:12px;">
        ${logoHtml}
        <div>
          <div style="font-size:20px;font-weight:bold;color:#1A1A18;">${infos.nom}</div>
          ${infos.secteur ? `<div style="font-size:12px;color:#6B6A64;">${infos.secteur}</div>` : ""}
        </div>
      </div>
      <div style="text-align:right;font-size:11px;color:#6B6A64;">
        ${infos.telephone ? `<div>${infos.telephone}</div>` : ""}
        ${infos.email ? `<div>${infos.email}</div>` : ""}
      </div>
    </div>
    <div style="margin-bottom:20px;">
      <div style="font-size:16px;font-weight:bold;color:#1A1A18;">${titre}</div>
      ${sousTitre ? `<div style="font-size:12px;color:#6B6A64;">${sousTitre}</div>` : ""}
    </div>`;
}

// Libellés bilingues du PDF (contexte document, indépendant de l'UI).
const L = {
  fr: {
    facture: "FACTURE", produit: "Produit", qte: "Qté", prixUnitaire: "Prix unitaire", montant: "Montant",
    sousTotal: "Sous-total", remise: "Remise", total: "Total", client: "Client", telephone: "Téléphone",
    localite: "Localité", entreprise: "Entreprise",
    mentions: "Mentions légales — vos données sont traitées conformément à notre politique de confidentialité. Document généré par CIKAP.",
  },
  en: {
    facture: "INVOICE", produit: "Product", qte: "Qty", prixUnitaire: "Unit price", montant: "Amount",
    sousTotal: "Subtotal", remise: "Discount", total: "Total", client: "Client", telephone: "Phone",
    localite: "Locality", entreprise: "Company",
    mentions: "Legal notice — your data is processed in accordance with our privacy policy. Document generated by CIKAP.",
  },
};

function piedHtml(langue: "fr" | "en" = "fr"): string {
  return `<div style="margin-top:30px;padding-top:12px;border-top:1px solid #E5E3DC;font-size:9px;color:#9B9A93;text-align:center;line-height:1.5;">${L[langue].mentions}</div>`;
}

const STYLE = `<style>
  * { font-family: Arial, sans-serif; }
  body { padding: 24px; color: #1A1A18; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { text-align: left; font-size: 11px; color: #6B6A64; padding: 8px 6px; border-bottom: 1px solid #E5E3DC; }
  td { font-size: 12px; padding: 8px 6px; border-bottom: 1px solid #F0EFEA; }
  .droite { text-align: right; }
  .total { font-size: 14px; font-weight: bold; }
</style>`;

// Nom de fichier lisible pour une facture : « Facture-Paul-2026-10-01.pdf ».
// Le nom du client est nettoyé (pas d'accents ni de caractères interdits dans
// un nom de fichier) ; à défaut, on utilise le numéro de facture.
function nomFichierFacture(facture: any, langue: "fr" | "en"): string {
  const date = facture.creeLe ? new Date(facture.creeLe) : new Date();
  const jj = String(date.getDate()).padStart(2, "0");
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const aaaa = date.getFullYear();
  const client = (facture.clientNom ?? "")
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  const base = langue === "fr" ? "Facture" : "Invoice";
  return client ? `${base}-${client}-${aaaa}-${mm}-${jj}.pdf` : `${base}-${facture.numero}.pdf`;
}

async function partager(html: string, nomFichier: string, ticket = false) {
  const options = ticket
    ? { html, width: LARGEUR_TICKET_PT, height: HAUTEUR_TICKET_PT }
    : { html };
  const { uri } = await Print.printToFileAsync(options);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: nomFichier });
  }
}

// Envoie directement vers l'écran d'impression du téléphone (sans partage).
// Sur Android, printAsync IGNORE width/height (cf. PrintModule.getAttributesFromOptions)
// : un ticket 80 mm passé en HTML s'affichait sur du A4. On génère donc d'abord
// le PDF à la bonne taille, puis on imprime le FICHIER — le dialogue d'impression
// reçoit alors des pages 80 mm, ce que les imprimantes thermiques attendent.
async function imprimerDirectement(html: string, ticket = false) {
  if (ticket && Platform.OS === "android") {
    const { uri } = await Print.printToFileAsync({ html, width: LARGEUR_TICKET_PT, height: HAUTEUR_TICKET_PT });
    await Print.printAsync({ uri });
    return;
  }
  await Print.printAsync(ticket ? { html, width: LARGEUR_TICKET_PT, height: HAUTEUR_TICKET_PT } : { html });
}

// Format « ticket de caisse » thermique : largeur standard 80 mm (≈ 227 pt),
// PAS du A4. expo-print prend les dimensions de page en points.
const LARGEUR_TICKET_PT = 227; // 80 mm
const HAUTEUR_TICKET_PT = 842; // hauteur de page (pagination automatique)

// Style « ticket de caisse » (modèle : assets/facture.jpg) — bande étroite
// type reçu thermique : police monospace, en-tête centré, séparateurs en
// pointillés, TOTAL en gros, mode de paiement, date centrée en bas.
const STYLE_TICKET = `<style>
  @page { size: 80mm auto; margin: 0; }
  * { font-family: "Courier New", Courier, monospace; color: #1a1a1a; }
  body { width: 80mm; margin: 0; padding: 10px 8px; }
  .centre { text-align: center; }
  .boutique { font-size: 17px; font-weight: bold; text-transform: uppercase; }
  .contact { font-size: 11px; }
  .separateur { border-top: 1px dashed #1a1a1a; margin: 10px 0; }
  .ligne { display: flex; justify-content: space-between; font-size: 12px; padding: 2px 0; }
  .ligne .detail { color: #444; font-size: 10px; }
  .total { font-size: 20px; font-weight: bold; padding: 6px 0; }
  .paiement { font-size: 12px; text-transform: uppercase; }
  .date { text-align: center; font-size: 12px; margin-top: 12px; }
  .merci { text-align: center; font-size: 9px; color: #555; margin-top: 14px; line-height: 1.5; }
</style>`;

// Construit le HTML ticket d'une facture (partagé par l'impression, le partage
// et l'envoi WhatsApp).
function construireHtmlFacture(infos: InfosBoutique, facture: any, lignes: any[], langue: "fr" | "en"): string {
  const l = L[langue];

  const date = facture.creeLe ? new Date(facture.creeLe) : new Date();
  const dateFormatee = `${String(date.getDate()).padStart(2, "0")}/${String(date.getMonth() + 1).padStart(2, "0")}/${date.getFullYear()}`;

  // Chaque article : nom (+ détail « qté × prix unitaire ») et montant à droite.
  const lignesHtml = lignes
    .map(
      (x) => `<div class="ligne">
        <div>
          <div>${x.produitNom}</div>
          <div class="detail">${x.quantite} × ${(x.prixUnitaire || 0).toLocaleString()} F</div>
        </div>
        <div>${((x.quantite || 0) * (x.prixUnitaire || 0)).toLocaleString()} F</div>
      </div>`
    )
    .join("");

  const clientHtml = facture.clientNom
    ? `<div class="ligne"><div>${l.client}</div><div>${facture.clientNom}</div></div>
       ${facture.clientTelephone ? `<div class="ligne"><div>${l.telephone}</div><div>${facture.clientTelephone}</div></div>` : ""}`
    : "";

  const html = `<html><head>${STYLE_TICKET}</head><body>
    <div class="centre">
      <div class="boutique">${infos.nom}</div>
      ${infos.telephone ? `<div class="contact">${infos.telephone}</div>` : ""}
      ${infos.email ? `<div class="contact">${infos.email}</div>` : ""}
    </div>
    <div class="separateur"></div>
    <div class="ligne"><div>${l.facture}</div><div>${facture.numero}</div></div>
    ${clientHtml}
    <div class="separateur"></div>
    ${lignesHtml}
    <div class="separateur"></div>
    ${facture.remise ? `<div class="ligne"><div>${l.remise}</div><div>- ${facture.remise.toLocaleString()} F</div></div>` : ""}
    <div class="ligne total"><div>${l.total}</div><div>${(facture.total || 0).toLocaleString()} F</div></div>
    <div class="ligne paiement"><div>${facture.statut === "payee" ? l.total : l.sousTotal}</div><div>${(facture.montantPaye || 0).toLocaleString()} F</div></div>
    <div class="date">${dateFormatee}</div>
    <div class="merci">${l.mentions}</div>
  </body></html>`;

  return html;
}

// Génère le FICHIER PDF d'une facture et renvoie son URI locale (sans ouvrir
// quoi que ce soit) — utilisé pour l'envoi WhatsApp depuis la fiche client.
export async function genererFichierFacturePdf(facture: any, lignes: any[], langue: "fr" | "en" = "fr"): Promise<string> {
  const infos = await obtenirInfosBoutique();
  const html = construireHtmlFacture(infos, facture, lignes, langue);
  const { uri } = await Print.printToFileAsync({ html, width: LARGEUR_TICKET_PT, height: HAUTEUR_TICKET_PT });
  return uri;
}

// Génère une facture PDF au format ticket de caisse. Par défaut, ouvre
// directement l'écran d'impression ; `exporter = true` génère un fichier à
// partager/télécharger.
export async function genererFacturePdf(facture: any, lignes: any[], langue: "fr" | "en" = "fr", exporter = false) {
  const infos = await obtenirInfosBoutique();
  const html = construireHtmlFacture(infos, facture, lignes, langue);

  if (exporter) {
    // Nom de fichier lisible : client + date (ex. Facture-Paul-2026-10-01.pdf),
    // au lieu d'un numéro technique seul.
    await partager(html, nomFichierFacture(facture, langue), true);
  } else {
    await imprimerDirectement(html, true);
  }
  await enregistrerActivite("impression", "ajout", `Facture ${facture.numero} imprimée`);
}

// ------------------------------------------------------------
// Rapports génériques : un utilitaire unique pour tout PDF « tableau ».
// Chaque page de l'app qui expose « Télécharger le rapport » construit ses
// sections et appelle genererRapportPdf — plus de HTML dupliqué.
// ------------------------------------------------------------

export type SectionRapport = {
  titre: string;
  colonnes: { libelle: string; aligneDroite?: boolean }[];
  lignes: (string | number)[][];
};

// Échappe les valeurs avant de les injecter dans le HTML : un nom de produit
// ou de client contenant `<` ou `&` casserait autrement le document.
function echapper(valeur: string): string {
  return valeur.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export async function genererRapportPdf({
  titre,
  sousTitre,
  sections,
  langue = "fr",
  nomFichier = "Rapport.pdf",
  descriptionActivite = "Rapport généré",
}: {
  titre: string;
  sousTitre?: string;
  sections: SectionRapport[];
  langue?: "fr" | "en";
  nomFichier?: string;
  descriptionActivite?: string;
}) {
  const infos = await obtenirInfosBoutique();

  const sectionsHtml = sections
    .filter((s) => s.lignes.length > 0)
    .map((s) => {
      const tete = s.colonnes
        .map((c) => `<th${c.aligneDroite ? ' class="droite"' : ""}>${echapper(c.libelle)}</th>`)
        .join("");
      const corps = s.lignes
        .map(
          (ligne) =>
            `<tr>${ligne
              .map((cellule, i) => `<td${s.colonnes[i]?.aligneDroite ? ' class="droite"' : ""}>${echapper(String(cellule))}</td>`)
              .join("")}</tr>`
        )
        .join("");
      return `<div style="font-size:13px;font-weight:bold;margin-top:18px;">${echapper(s.titre)}</div><table><tr>${tete}</tr>${corps}</table>`;
    })
    .join("");

  const html = `<html><head>${STYLE}</head><body>
    ${enteteHtml(infos, titre, sousTitre)}
    ${sectionsHtml}
    ${piedHtml(langue)}
  </body></html>`;

  await partager(html, nomFichier);
  await enregistrerActivite("impression", "ajout", descriptionActivite);
}

// Génère et partage un export comptable PDF (document complet).
export async function genererExportPdf(
  stats: {
    ca: number; benefice: number; ventes: number; parPaiement: Record<string, number>;
    produitsEnStock?: number; ruptures?: number;
    topProduits?: { nom: string; ventes: number; montant: number }[];
    topClients?: { nom: string; montant: number }[];
  },
  periodeLabel: string,
  langue: "fr" | "en" = "fr"
) {
  const sections: SectionRapport[] = [
    {
      titre: t("rapport_indicateurs", langue),
      colonnes: [{ libelle: t("rapport_col_indicateur", langue) }, { libelle: t("rapport_col_valeur", langue), aligneDroite: true }],
      lignes: [
        [t("dashboard_ca", langue), `${stats.ca.toLocaleString()} F`],
        [t("dashboard_benefice", langue), `${stats.benefice.toLocaleString()} F`],
        [t("dashboard_ventes", langue), stats.ventes],
        ...(stats.produitsEnStock != null ? [[t("export_produits_stock", langue), stats.produitsEnStock] as (string | number)[]] : []),
        ...(stats.ruptures != null ? [[t("export_ruptures", langue), stats.ruptures] as (string | number)[]] : []),
      ],
    },
    {
      titre: t("dashboard_par_paiement", langue),
      colonnes: [{ libelle: t("rapport_col_paiement", langue) }, { libelle: t("rapport_col_montant", langue), aligneDroite: true }],
      lignes: Object.entries(stats.parPaiement).map(([mode, montant]) => [mode, `${montant.toLocaleString()} F`]),
    },
    {
      titre: t("dashboard_top_produits", langue),
      colonnes: [
        { libelle: t("rapport_col_produit", langue) },
        { libelle: t("dashboard_ventes", langue), aligneDroite: true },
        { libelle: t("rapport_col_montant", langue), aligneDroite: true },
      ],
      lignes: (stats.topProduits ?? []).map((p) => [p.nom, p.ventes, `${p.montant.toLocaleString()} F`]),
    },
    {
      titre: t("dashboard_top_clients", langue),
      colonnes: [{ libelle: t("rapport_col_client", langue) }, { libelle: t("rapport_col_montant", langue), aligneDroite: true }],
      lignes: (stats.topClients ?? []).map((c) => [c.nom, `${c.montant.toLocaleString()} F`]),
    },
  ];

  await genererRapportPdf({
    titre: t("export_titre", langue).toUpperCase(),
    sousTitre: periodeLabel,
    sections,
    langue,
    nomFichier: "Export-comptable.pdf",
    descriptionActivite: "Export comptable généré",
  });
}

// Génère et partage un reçu de vente au format TICKET 80 mm (pas A4) : c'est
// le document qu'on envoie au client ou qu'on imprime sur imprimante thermique.
export async function genererRecuPdf(
  client: string | null,
  telephone: string | null,
  lignes: { nom: string; quantite: number; prixUnitaire: number }[],
  total: number,
  langue: "fr" | "en" = "fr"
) {
  const infos = await obtenirInfosBoutique();
  const l = L[langue];

  const dateFormatee = new Date().toLocaleDateString(langue === "fr" ? "fr-FR" : "en-US");

  const lignesHtml = lignes
    .map(
      (x) => `<div class="ligne">
        <div>
          <div>${echapper(x.nom)}</div>
          <div class="detail">${x.quantite} × ${(x.prixUnitaire || 0).toLocaleString()} F</div>
        </div>
        <div>${((x.quantite || 0) * (x.prixUnitaire || 0)).toLocaleString()} F</div>
      </div>`
    )
    .join("");

  const html = `<html><head>${STYLE_TICKET}</head><body>
    <div class="centre">
      <div class="boutique">${echapper(infos.nom)}</div>
      ${infos.telephone ? `<div class="contact">${echapper(infos.telephone)}</div>` : ""}
      ${infos.email ? `<div class="contact">${echapper(infos.email)}</div>` : ""}
    </div>
    <div class="separateur"></div>
    <div class="ligne"><div>${langue === "fr" ? "REÇU" : "RECEIPT"}</div><div>${dateFormatee}</div></div>
    ${client ? `<div class="ligne"><div>${l.client}</div><div>${echapper(client)}</div></div>` : ""}
    ${telephone ? `<div class="ligne"><div>${l.telephone}</div><div>${echapper(telephone)}</div></div>` : ""}
    <div class="separateur"></div>
    ${lignesHtml}
    <div class="separateur"></div>
    <div class="ligne total"><div>${l.total}</div><div>${(total || 0).toLocaleString()} F</div></div>
    <div class="merci">${l.mentions}</div>
  </body></html>`;

  // Nom de fichier lisible : « Recu-Paul-2026-10-01.pdf » (client + date).
  const d = new Date();
  const jj = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const aaaa = d.getFullYear();
  const clientNettoye = (client ?? "").normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  const base = langue === "fr" ? "Recu" : "Receipt";
  await partager(html, clientNettoye ? `${base}-${clientNettoye}-${aaaa}-${mm}-${jj}.pdf` : `${base}-${aaaa}-${mm}-${jj}.pdf`, true);
  await enregistrerActivite("impression", "ajout", "Reçu de vente partagé");
}