export type Pays = { code: string; indicatif: string; drapeau: string; nom: string };

export const PAYS: Pays[] = [
    // 🌍 Afrique francophone (priorité)
    { code: "CM", indicatif: "+237", drapeau: "🇨🇲", nom: "Cameroun" },
    { code: "CI", indicatif: "+225", drapeau: "🇨🇮", nom: "Côte d'Ivoire" },
    { code: "SN", indicatif: "+221", drapeau: "🇸🇳", nom: "Sénégal" },
    { code: "BJ", indicatif: "+229", drapeau: "🇧🇯", nom: "Bénin" },
    { code: "BF", indicatif: "+226", drapeau: "🇧🇫", nom: "Burkina Faso" },
    { code: "ML", indicatif: "+223", drapeau: "🇲🇱", nom: "Mali" },
    { code: "NE", indicatif: "+227", drapeau: "🇳🇪", nom: "Niger" },
    { code: "TG", indicatif: "+228", drapeau: "🇹🇬", nom: "Togo" },
    { code: "GN", indicatif: "+224", drapeau: "🇬🇳", nom: "Guinée" },
    { code: "CG", indicatif: "+242", drapeau: "🇨🇬", nom: "Congo" },
    { code: "CD", indicatif: "+243", drapeau: "🇨🇩", nom: "République démocratique du Congo" },
    { code: "CF", indicatif: "+236", drapeau: "🇨🇫", nom: "République centrafricaine" },
    { code: "TD", indicatif: "+235", drapeau: "🇹🇩", nom: "Tchad" },
    { code: "GA", indicatif: "+241", drapeau: "🇬🇦", nom: "Gabon" },
    { code: "GQ", indicatif: "+240", drapeau: "🇬🇶", nom: "Guinée équatoriale" },
    { code: "DJ", indicatif: "+253", drapeau: "🇩🇯", nom: "Djibouti" },
    { code: "KM", indicatif: "+269", drapeau: "🇰🇲", nom: "Comores" },
    { code: "MG", indicatif: "+261", drapeau: "🇲🇬", nom: "Madagascar" },
    { code: "MU", indicatif: "+230", drapeau: "🇲🇺", nom: "Maurice" },
    { code: "SC", indicatif: "+248", drapeau: "🇸🇨", nom: "Seychelles" },
  
    // 🌍 Autres pays africains
    { code: "DZ", indicatif: "+213", drapeau: "🇩🇿", nom: "Algérie" },
    { code: "AO", indicatif: "+244", drapeau: "🇦🇴", nom: "Angola" },
    { code: "BW", indicatif: "+267", drapeau: "🇧🇼", nom: "Botswana" },
    { code: "BI", indicatif: "+257", drapeau: "🇧🇮", nom: "Burundi" },
    { code: "CV", indicatif: "+238", drapeau: "🇨🇻", nom: "Cap-Vert" },
    { code: "EG", indicatif: "+20", drapeau: "🇪🇬", nom: "Égypte" },
    { code: "ER", indicatif: "+291", drapeau: "🇪🇷", nom: "Érythrée" },
    { code: "SZ", indicatif: "+268", drapeau: "🇸🇿", nom: "Eswatini" },
    { code: "ET", indicatif: "+251", drapeau: "🇪🇹", nom: "Éthiopie" },
    { code: "GM", indicatif: "+220", drapeau: "🇬🇲", nom: "Gambie" },
    { code: "GH", indicatif: "+233", drapeau: "🇬🇭", nom: "Ghana" },
    { code: "GW", indicatif: "+245", drapeau: "🇬🇼", nom: "Guinée-Bissau" },
    { code: "KE", indicatif: "+254", drapeau: "🇰🇪", nom: "Kenya" },
    { code: "LS", indicatif: "+266", drapeau: "🇱🇸", nom: "Lesotho" },
    { code: "LR", indicatif: "+231", drapeau: "🇱🇷", nom: "Libéria" },
    { code: "LY", indicatif: "+218", drapeau: "🇱🇾", nom: "Libye" },
    { code: "MW", indicatif: "+265", drapeau: "🇲🇼", nom: "Malawi" },
    { code: "MR", indicatif: "+222", drapeau: "🇲🇷", nom: "Mauritanie" },
    { code: "MA", indicatif: "+212", drapeau: "🇲🇦", nom: "Maroc" },
    { code: "MZ", indicatif: "+258", drapeau: "🇲🇿", nom: "Mozambique" },
    { code: "NA", indicatif: "+264", drapeau: "🇳🇦", nom: "Namibie" },
    { code: "NG", indicatif: "+234", drapeau: "🇳🇬", nom: "Nigeria" },
    { code: "RW", indicatif: "+250", drapeau: "🇷🇼", nom: "Rwanda" },
    { code: "ST", indicatif: "+239", drapeau: "🇸🇹", nom: "Sao Tomé-et-Principe" },
    { code: "SL", indicatif: "+232", drapeau: "🇸🇱", nom: "Sierra Leone" },
    { code: "SO", indicatif: "+252", drapeau: "🇸🇴", nom: "Somalie" },
    { code: "ZA", indicatif: "+27", drapeau: "🇿🇦", nom: "Afrique du Sud" },
    { code: "SS", indicatif: "+211", drapeau: "🇸🇸", nom: "Soudan du Sud" },
    { code: "SD", indicatif: "+249", drapeau: "🇸🇩", nom: "Soudan" },
    { code: "TZ", indicatif: "+255", drapeau: "🇹🇿", nom: "Tanzanie" },
    { code: "TN", indicatif: "+216", drapeau: "🇹🇳", nom: "Tunisie" },
    { code: "UG", indicatif: "+256", drapeau: "🇺🇬", nom: "Ouganda" },
    { code: "ZM", indicatif: "+260", drapeau: "🇿🇲", nom: "Zambie" },
    { code: "ZW", indicatif: "+263", drapeau: "🇿🇼", nom: "Zimbabwe" },
  ];
export const PAYS_PAR_DEFAUT = PAYS[0]; // Cameroun